# Generated by Django 3.2 on 2021-04-15 01:27

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prodName', models.CharField(max_length=150)),
                ('prodPrice', models.FloatField(null=True)),
                ('prodDate', models.DateTimeField(default=datetime.datetime.now)),
                ('prodDiscrption', models.TextField(null=True)),
                ('prodDescound', models.IntegerField(default=0)),
                ('prodRate', models.FloatField(default=0.0, null=True)),
                ('color', models.CharField(max_length=150)),
                ('img', models.ImageField(upload_to='product/img/%y/%m/%d')),
            ],
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categroyName', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='ProductImg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prodImg', models.ImageField(upload_to='product/img/%y/%m/%d')),
                ('prodNo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
            ],
        ),
        migrations.CreateModel(
            name='ProductColors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prodColor', models.CharField(max_length=150)),
                ('prodNo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='prodCate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.productcategory'),
        ),
    ]
